import { Item } from "types/Item";
import ProductItem from "../components/ProductItem";
import Head from "next/head";
import { BASE_URL } from "utils";
import { NextApiRequest, NextApiResponse } from "next/types";
import db from "prisma/db";

interface Props {
  items: Item[];
}

// export const getServerSideProps = async () => {
//   const response = await fetch(`${BASE_URL}/api/items`);
//   const items = await response?.json();

//   return { props: { items: items || [] } };
// };

export const getStaticProps = async () => {
  const items = await db.getItems();

  return { props: { items: items || [] } };
};

export default function Shop({ items }: Props) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-white">
        <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
          <h2 className="text-2xl font-bold tracking-tight text-gray-900">
            Products
          </h2>
          <div className="mt-6 grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
            {(items || []).map((item: Item) => (
              <ProductItem key={item.id} item={item} />
            ))}
          </div>
        </div>
      </div>
    </>
  );
}
