import { items } from "mocks/items";
import { Item } from "types/Item";
import ProductItem from "./components/ProductItem";
import { GetStaticProps } from "next/types";
import Head from "next/head";
import { useEffect } from "react";
import db from "prisma/db";
import { useQuery } from "react-query";

interface Props {
  items: Item[];
}

export const getStaticProps = async () => {
  const res = await fetch("http://localhost:3000/api/items");
  const items = await res.json();

  return { props: { items } };
};

export default function Shop({ items }: Props) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-white">
        <div className="mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8">
          <h2 className="text-2xl font-bold tracking-tight text-gray-900">
            Products
          </h2>
          {(items || []).map((item: Item) => (
            <ProductItem key={item.title} item={item} />
          ))}
        </div>
      </div>
    </>
  );
}
function graphqlClient() {
  throw new Error("Function not implemented.");
}
